In [ ]:
# Mengimpor pustaka NumPy sebagai np dan pustaka Pandas sebagai pd
import numpy as np
import pandas as pd

# Membaca file CSV yang berisi data perjalanan dari path tertentu dan menyimpannya ke dalam variabel df
# '/content/Travel details dataset.csv' adalah path (lokasi) dari file CSV yang akan dibaca
df = pd.read_csv("/content/Travel details dataset.csv")
df

,Trip ID,Destination,Start date,End date,Duration (days),Traveler name,Traveler age,Traveler gender,Traveler nationality,Accommodation type,Accommodation cost,Transportation type,Transportation cost
0,1,"London, UK",5/1/2023,5/8/2023,7.0,John Smith,35.0,Male,American,Hotel,1200,Flight,600
1,2,"Phuket, Thailand",6/15/2023,6/20/2023,5.0,Jane Doe,28.0,Female,Canadian,Resort,800,Flight,500
2,3,"Bali, Indonesia",7/1/2023,7/8/2023,7.0,David Lee,45.0,Male,Korean,Villa,1000,Flight,700
3,4,"New York, USA",8/15/2023,8/29/2023,14.0,Sarah Johnson,29.0,Female,British,Hotel,2000,Flight,1000
4,5,"Tokyo, Japan",9/10/2023,9/17/2023,7.0,Kim Nguyen,26.0,Female,Vietnamese,Airbnb,700,Train,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,135,"Rio de Janeiro, Brazil",8/1/2023,8/10/2023,9.0,Jose Perez,37.0,Male,Brazilian,Hostel,2500,Car,2000
135,136,"Vancouver, Canada",8/15/2023,8/21/2023,6.0,Emma Wilson,29.0,Female,Canadian,Hotel,5000,Airplane,3000
136,137,"Bangkok, Thailand",9/1/2023,9/8/2023,7.0,Ryan Chen,34.0,Male,Chinese,Hostel,2000,Train,1000
137,138,"Barcelona, Spain",9/15/2023,9/22/2023,7.0,Sofia Rodriguez,25.0,Female,Spanish,Airbnb,6000,Airplane,2500
138,139,"Auckland, New Zealand",10/1/2023,10/8/2023,7.0,William Brown,39.0,Male,New Zealander,Hotel,7000,Train,2500

In [ ]:
df.head # Menampilkan beberapa baris pertama (secara default lima baris pertama) dari DataFrame df

<bound method NDFrame.head of      Trip ID             Destination Start date   End date  Duration (days)  \
0          1              London, UK   5/1/2023   5/8/2023              7.0
1          2        Phuket, Thailand  6/15/2023  6/20/2023              5.0
2          3         Bali, Indonesia   7/1/2023   7/8/2023              7.0
3          4           New York, USA  8/15/2023  8/29/2023             14.0
4          5            Tokyo, Japan  9/10/2023  9/17/2023              7.0
..       ...                     ...        ...        ...              ...
134      135  Rio de Janeiro, Brazil   8/1/2023  8/10/2023              9.0
135      136       Vancouver, Canada  8/15/2023  8/21/2023              6.0
136      137       Bangkok, Thailand   9/1/2023   9/8/2023              7.0
137      138        Barcelona, Spain  9/15/2023  9/22/2023              7.0
138      139   Auckland, New Zealand  10/1/2023  10/8/2023              7.0

       Traveler name  Traveler age Traveler gender Traveler nationality  \
0         John Smith          35.0            Male             American
1           Jane Doe          28.0          Female             Canadian
2          David Lee          45.0            Male               Korean
3      Sarah Johnson          29.0          Female              British
4         Kim Nguyen          26.0          Female           Vietnamese
..               ...           ...             ...                  ...
134       Jose Perez          37.0            Male            Brazilian
135      Emma Wilson          29.0          Female             Canadian
136        Ryan Chen          34.0            Male              Chinese
137  Sofia Rodriguez          25.0          Female              Spanish
138    William Brown          39.0            Male        New Zealander

    Accommodation type Accommodation cost Transportation type  \
0                Hotel               1200              Flight
1               Resort                800              Flight
2                Villa               1000              Flight
3                Hotel               2000              Flight
4               Airbnb                700               Train
..                 ...                ...                 ...
134             Hostel               2500                 Car
135              Hotel               5000            Airplane
136             Hostel               2000               Train
137             Airbnb               6000            Airplane
138              Hotel               7000               Train

    Transportation cost
0                   600
1                   500
2                   700
3                  1000
4                   200
..                  ...
134                2000
135                3000
136                1000
137                2500
138                2500

[139 rows x 13 columns]>

In [ ]:
df=df.drop(columns=["Destination","Start date","End date","Trip ID", "Traveler name","Duration (days)"], axis=0) #menghapus beberapa kolom pada dataframe
df

,Traveler age,Traveler gender,Traveler nationality,Accommodation type,Accommodation cost,Transportation type,Transportation cost
0,35.0,Male,American,Hotel,1200,Flight,600
1,28.0,Female,Canadian,Resort,800,Flight,500
2,45.0,Male,Korean,Villa,1000,Flight,700
3,29.0,Female,British,Hotel,2000,Flight,1000
4,26.0,Female,Vietnamese,Airbnb,700,Train,200
...,...,...,...,...,...,...,...
134,37.0,Male,Brazilian,Hostel,2500,Car,2000
135,29.0,Female,Canadian,Hotel,5000,Airplane,3000
136,34.0,Male,Chinese,Hostel,2000,Train,1000
137,25.0,Female,Spanish,Airbnb,6000,Airplane,2500
138,39.0,Male,New Zealander,Hotel,7000,Train,2500

In [ ]:
class Node:
    def __init__(self, Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost): # Inisialisasi atribut-atribut dari objek Node
        self.Traveler_age = Traveler_age  # Usia traveler
        self.Traveler_gender = Traveler_gender  # Jenis kelamin traveler
        self.Travel_nasionality = Travel_nasionality  # Kebangsaan traveler
        self.Accomodation_type = Accomodation_type  # Tipe akomodasi yang digunakan oleh traveler
        self.Accomodation_cost = Accomodation_cost  # Biaya akomodasi traveler
        self.Transportation_type = Transportation_type  # Tipe transportasi yang digunakan oleh traveler
        self.Transportation_cost = Transportation_cost  # Biaya transportasi traveler
        self.next = None  # Pointer ke Node selanjutnya dalam linked list


class LinkedList: #kelas linked list
    def __init__(self):
        self.head = None #head belum ada

    def sort(self):
      if self.head is None:  # Jika linked list kosong, tidak perlu dilakukan sorting
        return

      last = self.head  # Inisialisasi variabel last untuk menunjuk ke node terakhir
      while (last.next):  # Mencari node terakhir dalam linked list
        last = last.next

      current = self.head  # Inisialisasi variabel current untuk iterasi pertama pada linked list
      while current.next:  # Iterasi pada linked list
        if current.data > current.next.data:  # Membandingkan data node saat ini dengan data node berikutnya
            # Jika data node saat ini lebih besar dari data node berikutnya, tukar posisinya
            current.data, current.next.data = current.next.data, current.data
        current = current.next  # Pindah ke node berikutnya


    def add_at_beginning(self, Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost):
      new_node = Node(Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost) # Membuat node baru dengan data yang diberikan
      new_node.next = self.head # Mengatur pointer node baru agar menunjuk ke node yang sebelumnya menjadi kepala linked list

    # Mengatur node baru sebagai kepala linked list
      self.head = new_node  # Memberikan node baru sebagai kepala linked list


    def add_at_end(self, Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost):
      new_node = Node(Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost) # Membuat node baru dengan data yang diberikan
      if self.head is None:  # Memeriksa apakah linked list kosong
        self.head = new_node  # Jika linked list kosong, node baru menjadi node pertama
        return
      last = self.head  # Inisialisasi variabel last untuk menunjuk ke node terakhir
      while (last.next):  # Mencari node terakhir dalam linked list
        last = last.next
      last.next = new_node  # Menambahkan node baru setelah node terakhir


    def insert_at_beginning(self, Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost):
      new_node = Node(Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost) # Membuat node baru dengan data yang diberikan

    # Menyisipkan node baru ke awal linked list
      new_node.next = self.head  # Mengatur pointer node baru agar menunjuk ke node yang sebelumnya menjadi kepala linked list
      self.head = new_node  # Mengatur node baru sebagai kepala linked list


    def insert_at_end(self, Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost):
      new_node = Node(Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost) # Membuat node baru dengan data yang diberikan
      if not self.head:  # Memeriksa apakah linked list kosong
        self.head = new_node  # Jika linked list kosong, node baru menjadi node pertama
        return

    # Jika linked list tidak kosong, tambahkan node baru di belakang node terakhir
      current = self.head
      while current.next:
        current = current.next
      current.next = new_node  # Menambahkan node baru setelah node terakhir


    def delete_from_beginning(self):
        if not self.head: #memeriksa linked list lagi
            print("List is empty. Nothing to delete.")
        else:
            self.head = self.head.next #mengganti head linked list ke node selanjutnya

    def delete_from_end(self):
      if not self.head:  # Memeriksa apakah linked list kosong
        print("List is empty. Nothing to delete.")
      elif not self.head.next:  # Memeriksa apakah linked list hanya memiliki satu node
        self.head = None  # Jika hanya ada satu node, maka hapus node tersebut
      else:
        current = self.head
        while current.next.next:  # Mencari node kedua terakhir dalam linked list
            current = current.next
        current.next = None  # Menghapus node terakhir dengan mengubah pointer node kedua terakhir menjadi None


    def print_data(self):
      current = self.head
      if not current:
        print("List is empty.")  # Memeriksa apakah linked list kosong
      else:
        print("Data in the list Traveler:")  # Mencetak data dari linked list
        while current:
            # Mencetak data dari setiap node dalam linked list
            print(f"Age: {current.Traveler_age}, Gender: {current.Traveler_gender}, Nationality: {current.Travel_nasionality}, Accommodation Type: {current.Accomodation_type}, Accommodation Cost: {current.Accomodation_cost}, Transportation Type: {current.Transportation_type}, Transportation Cost: {current.Transportation_cost}")
            current = current.next


    def display(self):
      elements = []  # Inisialisasi list untuk menyimpan elemen
      current_node = self.head  # Mulai dari kepala linked list

    # Mengambil setiap elemen dari linked list
      while current_node:
        elements.append(str(current_node.data))  # Menambahkan data dari setiap node ke dalam list
        current_node = current_node.next  # Pindah ke node berikutnya

    # Mencetak elemen-elemen dari linked list yang telah dikumpulkan
      print(" -> ".join(elements))  # Menggabungkan elemen-elemen dalam list sebagai output dengan pemisah " -> "


    def reverse(self):
      prev_node = None  # Node sebelumnya diinisialisasi sebagai None
      current_node = self.head  # Node saat ini diinisialisasi sebagai kepala linked list

    # Melakukan proses pembalikan linked list
      while current_node is not None:
        next_node = current_node.next  # Menyimpan referensi ke node selanjutnya
        current_node.next = prev_node  # Merubah pointer ke node sebelumnya untuk melakukan pembalikan
        prev_node = current_node  # Pindah ke node berikutnya
        current_node = next_node  # Pindah ke node selanjutnya

      self.head = prev_node  # Mengubah kepala linked list menjadi node terakhir setelah pembalikan

In [ ]:
def append_to_list(self, data):
    if not self.head:  # Memeriksa apakah linked list kosong
        self.head = Node(data)  # Jika kosong, node baru akan menjadi node pertama
    else:
        current = self.head
        while current.next:  # Mencari node terakhir dalam linked list
            current = current.next
        current.next = Node(data)  # Menambahkan node baru setelah node terakhir

In [ ]:
df =df.values.tolist() # Mengonversi DataFrame menjadi list menggunakan metode values.tolist()
df

[[35.0, 'Male', 'American', 'Hotel', '1200', 'Flight', '600'],
 [28.0, 'Female', 'Canadian', 'Resort', '800', 'Flight', '500'],
 [45.0, 'Male', 'Korean', 'Villa', '1000', 'Flight', '700'],
 [29.0, 'Female', 'British', 'Hotel', '2000', 'Flight', '1000'],
 [26.0, 'Female', 'Vietnamese', 'Airbnb', '700', 'Train', '200'],
 [42.0, 'Male', 'American', 'Hotel', '1500', 'Flight', '800'],
 [33.0, 'Female', 'Australian', 'Hostel', '500', 'Flight', '1200'],
 [25.0, 'Male', 'Brazilian', 'Airbnb', '900', 'Flight', '600'],
 [31.0, 'Female', 'Dutch', 'Hotel', '1200', 'Train', '200'],
 [39.0, 'Male', 'Emirati', 'Resort', '2500', 'Flight', '800'],
 [27.0, 'Female', 'Mexican', 'Hotel', '1000', 'Flight', '500'],
 [36.0, 'Male', 'Spanish', 'Airbnb', '800', 'Train', '100'],
 [29.0, 'Female', 'Chinese', 'Resort', '3000', 'Flight', '1200'],
 [48.0, 'Male', 'German', 'Hotel', '1400', 'Flight', '700'],
 [26.0, 'Female', 'Moroccan', 'Riad', '600', 'Flight', '400'],
 [32.0, 'Male', 'Scottish', 'Hotel', '900', 'Train', '150'],
 [30.0, 'Female', 'American', 'Hotel', '$900 ', 'Plane', '$400 '],
 [28.0, 'Male', 'Chinese', 'Resort', '$1,500 ', 'Plane', '$700 '],
 [35.0, 'Female', 'British', 'Hotel', '$1,200 ', 'Train', '$150 '],
 [45.0, 'Male', 'Japanese', 'Hotel', '$1,200 ', 'Plane', '$800 '],
 [27.0, 'Female', 'American', 'Airbnb', '$600 ', 'Bus', '$100 '],
 [32.0, 'Male', 'Australian', 'Hotel', '$1,000 ', 'Plane', '$600 '],
 [29.0, 'Female', 'Italian', 'Airbnb', '$700 ', 'Train', '$80 '],
 [40.0, 'Male', 'Indian', 'Hostel', '$400 ', 'Plane', '$500 '],
 [24.0, 'Female', 'Vietnamese', 'Hotel', '$1,400 ', 'Train', '$100 '],
 [34.0, 'Male', 'Korean', 'Resort', '$2,000 ', 'Plane', '$800 '],
 [31.0, 'Female', 'Spanish', 'Hotel', '$1,100 ', 'Train', '$150 '],
 [30.0, 'Female', 'American', 'Hotel', '$800 ', 'Plane', '$500 '],
 [45.0, 'Male', 'Canadian', 'Hostel', '$200 ', 'Train', '$150 '],
 [25.0, 'Male', 'Korean', 'Airbnb', '$600 ', 'Car rental', '$300 '],
 [28.0, 'Female', 'British', 'Hotel', '$1,000 ', 'Car rental', '$500 '],
 [33.0, 'Female', 'Australian', 'Hostel', '$150 ', 'Bus', '$50 '],
 [20.0, 'Male', 'American', 'Airbnb', '$400 ', 'Plane', '$600 '],
 [37.0, 'Female', 'Canadian', 'Hotel', '$700 ', 'Train', '$100 '],
 [42.0, 'Male', 'British', 'Airbnb', '$500 ', 'Plane', '$800 '],
 [31.0, 'Female', 'American', 'Hostel', '$180 ', 'Train', '$120 '],
 [27.0, 'Male', 'Korean', 'Hotel', '$900 ', 'Car rental', '$400 '],
 [38.0, 'Female', 'Australian', 'Airbnb', '$350 ', 'Bus', '$75 '],
 [25.0, 'Female', 'American', 'Hotel', '1400', 'Plane', '600'],
 [33.0, 'Male', 'Canadian', 'Airbnb', '800', 'Train', '150'],
 [28.0, 'Female', 'Chinese', 'Hostel', '500', 'Plane', '900'],
 [45.0, 'Male', 'American', 'Resort', '2200', 'Plane', '800'],
 [30.0, 'Female', 'Brazilian', 'Hotel', '1200', 'Plane', '700'],
 [55.0, 'Male', 'British', 'Airbnb', '900', 'Train', '100'],
 [27.0, 'Female', 'Spanish', 'Hostel', '600', 'Plane', '600'],
 [41.0, 'Male', 'American', 'Hotel', '1500', 'Plane', '500'],
 [29.0, 'Female', 'Indian', 'Airbnb', '500', 'Bus', '50'],
 [24.0, 'Male', 'Korean', 'Hostel', '400', 'Train', '150'],
 [31.0, 'Female', 'Dutch', 'Hotel', '1100', 'Plane', '700'],
 [31.0, 'Female', 'Canadian', 'Hotel', '$1,200 ', 'Train', '$300 '],
 [25.0, 'Male', 'American', 'Hostel', '$500 ', 'Bus', '$100 '],
 [27.0, 'Female', 'South Korean', 'Airbnb', '$900 ', 'Car rental', '$200 '],
 [28.0, 'Female', 'Canadian', 'Hotel', '$1,400 ', 'Flight', '$800 '],
 [30.0, 'Male', 'Brazilian', 'Airbnb', '$800 ', 'Train', '$150 '],
 [23.0, 'Female', 'Indian', 'Hostel', '$400 ', 'Bus', '$50 '],
 [35.0, 'Male', 'British', 'Hotel', '$1,000 ', 'Train', '$200 '],
 [29.0, 'Female', 'Spanish', 'Airbnb', '$700 ', 'Car rental', '$250 '],
 [27.0, 'Male', 'South Korean', 'Hostel', '$500 ', 'Subway', '$20 '],
 [26.0, 'Male', 'Chinese', 'Hotel', '$1,200 ', 'Car rental', '$300 '],
 [33.0, 'Female', 'Italian', 'Airbnb', '$800 ', 'Train', '$100 '],
 [35.0, 'Female', 'American', 'Hotel', '1200', 'Plane', '800'],
 [28.0, 'Male', 'Japanese', 'Hostel', '400', 'Train', '300'],
 [29.0, 'Female', 'British', 'Vacation rental', '800', 'Car rental', '200'],
 [43.0, 'Male', 'Australian', 'Hotel', '1500', 'Plane', '1200'],
 [31.0, 'Female', 'Spanish', 'Vacation rental', '900', 'Plane', '700'],
 [27.0, 'Male', 'American', 'Resort', '2200', 'Plane', '1000'],
 [39.0, 'Female', 'French', 'Hotel', '1100', 'Train', '200'],
 [25.0, 'Male', 'American', 'Vacation rental', '1000', 'Plane', '800'],
 [33.0, 'Female', 'Indian', 'Hostel', '300', 'Plane', '700'],
 [41.0, 'Male', 'Italian', 'Hotel', '1300', 'Train', '100'],
 [37.0, 'Female', 'British', 'Resort', '1800', 'Plane', '1000'],
 [nan, nan, nan, nan, nan, nan, nan],
 [35.0, 'Female', 'South Korean', 'Resort', '500 USD', 'Plane', '800 USD'],
 [29.0, 'Male', 'American', 'Hotel', '1000 USD', 'Train', '200 USD'],
 [42.0, 'Female', 'Mexican', 'Resort', '800 USD', 'Plane', '500 USD'],
 [46.0, 'Male', 'British', 'Hotel', '1200 USD', 'Plane', '700 USD'],
 [31.0, 'Male', 'South African', 'Guesthouse', '400 USD', 'Car', '300 USD'],
 [25.0, 'Female', 'Taiwanese', 'Resort', '600 USD', 'Plane', '700 USD'],
 [38.0, 'Male', 'Australian', 'Hotel', '900 USD', 'Plane', '600 USD'],
 [27.0, 'Female', 'Korean', 'Hotel', '400 USD', 'Plane', '400 USD'],
 [60.0, 'Male', 'American', 'Hotel', '1500 USD', 'Plane', '1000 USD'],
 [32.0, 'Female', 'British', 'Resort', '700 USD', 'Plane', '800 USD'],
 [41.0, 'Male', 'American', 'Hotel', '100', nan, nan],
 [35.0, 'Male', 'American', 'Hotel', '800 USD', 'Plane', '500 USD'],
 [28.0, 'Female', 'Korean', 'Airbnb', '500 USD', 'Train', '300 USD'],
 [42.0, 'Female', 'Spanish', 'Resort', '1200 USD', 'Plane', '700 USD'],
 [45.0, 'Male', 'Australian', 'Hotel', '900 USD', 'Plane', '600 USD'],
 [31.0, 'Female', 'American', 'Airbnb', '700 USD', 'Car rental', '200 USD'],
 [29.0, 'Male', 'British', 'Hostel', '300 USD', 'Plane', '400 USD'],
 [24.0, 'Female', 'Emirati', 'Hotel', '1000 USD', 'Plane', '800 USD'],
 [26.0, 'Male', 'Vietnamese', 'Airbnb', '400 USD', 'Train', '100 USD'],
 [30.0, 'Female', 'Italian', 'Hostel', '200 USD', 'Plane', '350 USD'],
 [33.0, 'Male', 'Indonesian', 'Villa', '1500 USD', 'Car rental', '300 USD'],
 [27.0, 'Female', 'Korean', 'Hotel', '800 USD', 'Train', '150 USD'],
 [35.0, 'Male', 'USA', 'Hotel', '$500 ', 'Plane', '$800 '],
 [28.0, 'Female', 'Canada', 'Airbnb', '$400 ', 'Train', '$200 '],
 [45.0, 'Male', 'South Korea', 'Hostel', '$200 ', 'Plane', '$1,200 '],
 [37.0, 'Female', 'UK', 'Hotel', '$600 ', 'Plane', '$700 '],
 [50.0, 'Male', 'China', 'Airbnb', '$800 ', 'Car rental', '$300 '],
 [31.0, 'Female', 'Taiwan', 'Hotel', '$700 ', 'Plane', '$900 '],
 [42.0, 'Male', 'Japan', 'Hostel', '$300 ', 'Train', '$100 '],
 [27.0, 'Female', 'Spain', 'Airbnb', '$500 ', 'Plane', '$1,500 '],
 [33.0, 'Male', 'Brazil', 'Hotel', '$900 ', 'Car rental', '$400 '],
 [29.0, 'Female', 'South Korea', 'Villa', '$1,200 ', 'Plane', '$1,000 '],
 [41.0, 'Male', 'Germany', 'Hotel', '$600 ', 'Train', '$150 '],
 [35.0, 'Male', 'USA', 'Hotel', '1000', 'Plane', '800'],
 [28.0, 'Female', 'South Korea', 'Airbnb', '800', 'Train', '500'],
 [42.0, 'Male', 'Hong Kong', 'Hotel', '1200', 'Car rental', '200'],
 [30.0, 'Female', 'Taiwan', 'Resort', '1500', 'Plane', '1200'],
 [26.0, 'Male', 'Canada', 'Hostel', '300', 'Plane', '900'],
 [38.0, 'Female', 'United Kingdom', 'Hotel', '900', 'Train', '150'],
 [45.0, 'Male', 'Singapore', 'Villa', '2000', 'Plane', '700'],
 [31.0, 'Female', 'Italy', 'Hotel', '1100', 'Train', '250'],
 [27.0, 'Male', 'Greece', 'Airbnb', '1000', 'Ferry', '150'],
 [29.0,
  'Female',
  'United Arab Emirates',
  'Hotel',
  '1500',
  'Car rental',
  '300'],
 [33.0, 'Male', 'Cambodia', 'Hostel', '200', 'Plane', '500'],
 [32.0, 'Female', 'American', 'Hotel', '1000', 'Plane', '700'],
 [47.0, 'Male', 'Canadian', 'Hotel', '1200', 'Train', '500'],
 [26.0, 'Female', 'Chinese', 'Airbnb', '800', 'Plane', '1000'],
 [38.0, 'Male', 'Korean', 'Hotel', '900', 'Train', '400'],
 [29.0, 'Female', 'Korean', 'Hostel', '500', 'Plane', '800'],
 [41.0, 'Male', 'American', 'Hotel', '1300', 'Plane', '600'],
 [35.0, 'Female', 'Korean', 'Airbnb', '700', 'Plane', '900'],
 [24.0, 'Male', 'Korean', 'Hotel', '1200', 'Plane', '700'],
 [30.0, 'Female', 'Chinese', 'Airbnb', '900', 'Plane', '1000'],
 [28.0, 'Male', 'American', 'Hostel', '400', 'Plane', '700'],
 [33.0, 'Female', 'Canadian', 'Hotel', '800', 'Plane', '800'],
 [nan, nan, nan, nan, nan, nan, nan],
 [35.0, 'Male', 'American', 'Hotel', '5000', 'Airplane', '2500'],
 [28.0, 'Female', 'British', 'Airbnb', '7000', 'Train', '1500'],
 [45.0, 'Male', 'South African', 'Hostel', '3000', 'Car', '2000'],
 [31.0, 'Female', 'Australian', 'Hotel', '6000', 'Airplane', '3000'],
 [42.0, 'Male', 'Korean', 'Airbnb', '4000', 'Train', '1500'],
 [27.0, 'Female', 'American', 'Hotel', '8000', 'Airplane', '2500'],
 [37.0, 'Male', 'Brazilian', 'Hostel', '2500', 'Car', '2000'],
 [29.0, 'Female', 'Canadian', 'Hotel', '5000', 'Airplane', '3000'],
 [34.0, 'Male', 'Chinese', 'Hostel', '2000', 'Train', '1000'],
 [25.0, 'Female', 'Spanish', 'Airbnb', '6000', 'Airplane', '2500'],
 [39.0, 'Male', 'New Zealander', 'Hotel', '7000', 'Train', '2500']]

In [ ]:
df.reverse() # Membalik urutan elemen dalam list menggunakan metode reverse()
df # Menampilkan list setelah pengurutan dibalik

[[39.0, 'Male', 'New Zealander', 'Hotel', '7000', 'Train', '2500'],
 [25.0, 'Female', 'Spanish', 'Airbnb', '6000', 'Airplane', '2500'],
 [34.0, 'Male', 'Chinese', 'Hostel', '2000', 'Train', '1000'],
 [29.0, 'Female', 'Canadian', 'Hotel', '5000', 'Airplane', '3000'],
 [37.0, 'Male', 'Brazilian', 'Hostel', '2500', 'Car', '2000'],
 [27.0, 'Female', 'American', 'Hotel', '8000', 'Airplane', '2500'],
 [42.0, 'Male', 'Korean', 'Airbnb', '4000', 'Train', '1500'],
 [31.0, 'Female', 'Australian', 'Hotel', '6000', 'Airplane', '3000'],
 [45.0, 'Male', 'South African', 'Hostel', '3000', 'Car', '2000'],
 [28.0, 'Female', 'British', 'Airbnb', '7000', 'Train', '1500'],
 [35.0, 'Male', 'American', 'Hotel', '5000', 'Airplane', '2500'],
 [nan, nan, nan, nan, nan, nan, nan],
 [33.0, 'Female', 'Canadian', 'Hotel', '800', 'Plane', '800'],
 [28.0, 'Male', 'American', 'Hostel', '400', 'Plane', '700'],
 [30.0, 'Female', 'Chinese', 'Airbnb', '900', 'Plane', '1000'],
 [24.0, 'Male', 'Korean', 'Hotel', '1200', 'Plane', '700'],
 [35.0, 'Female', 'Korean', 'Airbnb', '700', 'Plane', '900'],
 [41.0, 'Male', 'American', 'Hotel', '1300', 'Plane', '600'],
 [29.0, 'Female', 'Korean', 'Hostel', '500', 'Plane', '800'],
 [38.0, 'Male', 'Korean', 'Hotel', '900', 'Train', '400'],
 [26.0, 'Female', 'Chinese', 'Airbnb', '800', 'Plane', '1000'],
 [47.0, 'Male', 'Canadian', 'Hotel', '1200', 'Train', '500'],
 [32.0, 'Female', 'American', 'Hotel', '1000', 'Plane', '700'],
 [33.0, 'Male', 'Cambodia', 'Hostel', '200', 'Plane', '500'],
 [29.0,
  'Female',
  'United Arab Emirates',
  'Hotel',
  '1500',
  'Car rental',
  '300'],
 [27.0, 'Male', 'Greece', 'Airbnb', '1000', 'Ferry', '150'],
 [31.0, 'Female', 'Italy', 'Hotel', '1100', 'Train', '250'],
 [45.0, 'Male', 'Singapore', 'Villa', '2000', 'Plane', '700'],
 [38.0, 'Female', 'United Kingdom', 'Hotel', '900', 'Train', '150'],
 [26.0, 'Male', 'Canada', 'Hostel', '300', 'Plane', '900'],
 [30.0, 'Female', 'Taiwan', 'Resort', '1500', 'Plane', '1200'],
 [42.0, 'Male', 'Hong Kong', 'Hotel', '1200', 'Car rental', '200'],
 [28.0, 'Female', 'South Korea', 'Airbnb', '800', 'Train', '500'],
 [35.0, 'Male', 'USA', 'Hotel', '1000', 'Plane', '800'],
 [41.0, 'Male', 'Germany', 'Hotel', '$600 ', 'Train', '$150 '],
 [29.0, 'Female', 'South Korea', 'Villa', '$1,200 ', 'Plane', '$1,000 '],
 [33.0, 'Male', 'Brazil', 'Hotel', '$900 ', 'Car rental', '$400 '],
 [27.0, 'Female', 'Spain', 'Airbnb', '$500 ', 'Plane', '$1,500 '],
 [42.0, 'Male', 'Japan', 'Hostel', '$300 ', 'Train', '$100 '],
 [31.0, 'Female', 'Taiwan', 'Hotel', '$700 ', 'Plane', '$900 '],
 [50.0, 'Male', 'China', 'Airbnb', '$800 ', 'Car rental', '$300 '],
 [37.0, 'Female', 'UK', 'Hotel', '$600 ', 'Plane', '$700 '],
 [45.0, 'Male', 'South Korea', 'Hostel', '$200 ', 'Plane', '$1,200 '],
 [28.0, 'Female', 'Canada', 'Airbnb', '$400 ', 'Train', '$200 '],
 [35.0, 'Male', 'USA', 'Hotel', '$500 ', 'Plane', '$800 '],
 [27.0, 'Female', 'Korean', 'Hotel', '800 USD', 'Train', '150 USD'],
 [33.0, 'Male', 'Indonesian', 'Villa', '1500 USD', 'Car rental', '300 USD'],
 [30.0, 'Female', 'Italian', 'Hostel', '200 USD', 'Plane', '350 USD'],
 [26.0, 'Male', 'Vietnamese', 'Airbnb', '400 USD', 'Train', '100 USD'],
 [24.0, 'Female', 'Emirati', 'Hotel', '1000 USD', 'Plane', '800 USD'],
 [29.0, 'Male', 'British', 'Hostel', '300 USD', 'Plane', '400 USD'],
 [31.0, 'Female', 'American', 'Airbnb', '700 USD', 'Car rental', '200 USD'],
 [45.0, 'Male', 'Australian', 'Hotel', '900 USD', 'Plane', '600 USD'],
 [42.0, 'Female', 'Spanish', 'Resort', '1200 USD', 'Plane', '700 USD'],
 [28.0, 'Female', 'Korean', 'Airbnb', '500 USD', 'Train', '300 USD'],
 [35.0, 'Male', 'American', 'Hotel', '800 USD', 'Plane', '500 USD'],
 [41.0, 'Male', 'American', 'Hotel', '100', nan, nan],
 [32.0, 'Female', 'British', 'Resort', '700 USD', 'Plane', '800 USD'],
 [60.0, 'Male', 'American', 'Hotel', '1500 USD', 'Plane', '1000 USD'],
 [27.0, 'Female', 'Korean', 'Hotel', '400 USD', 'Plane', '400 USD'],
 [38.0, 'Male', 'Australian', 'Hotel', '900 USD', 'Plane', '600 USD'],
 [25.0, 'Female', 'Taiwanese', 'Resort', '600 USD', 'Plane', '700 USD'],
 [31.0, 'Male', 'South African', 'Guesthouse', '400 USD', 'Car', '300 USD'],
 [46.0, 'Male', 'British', 'Hotel', '1200 USD', 'Plane', '700 USD'],
 [42.0, 'Female', 'Mexican', 'Resort', '800 USD', 'Plane', '500 USD'],
 [29.0, 'Male', 'American', 'Hotel', '1000 USD', 'Train', '200 USD'],
 [35.0, 'Female', 'South Korean', 'Resort', '500 USD', 'Plane', '800 USD'],
 [nan, nan, nan, nan, nan, nan, nan],
 [37.0, 'Female', 'British', 'Resort', '1800', 'Plane', '1000'],
 [41.0, 'Male', 'Italian', 'Hotel', '1300', 'Train', '100'],
 [33.0, 'Female', 'Indian', 'Hostel', '300', 'Plane', '700'],
 [25.0, 'Male', 'American', 'Vacation rental', '1000', 'Plane', '800'],
 [39.0, 'Female', 'French', 'Hotel', '1100', 'Train', '200'],
 [27.0, 'Male', 'American', 'Resort', '2200', 'Plane', '1000'],
 [31.0, 'Female', 'Spanish', 'Vacation rental', '900', 'Plane', '700'],
 [43.0, 'Male', 'Australian', 'Hotel', '1500', 'Plane', '1200'],
 [29.0, 'Female', 'British', 'Vacation rental', '800', 'Car rental', '200'],
 [28.0, 'Male', 'Japanese', 'Hostel', '400', 'Train', '300'],
 [35.0, 'Female', 'American', 'Hotel', '1200', 'Plane', '800'],
 [33.0, 'Female', 'Italian', 'Airbnb', '$800 ', 'Train', '$100 '],
 [26.0, 'Male', 'Chinese', 'Hotel', '$1,200 ', 'Car rental', '$300 '],
 [27.0, 'Male', 'South Korean', 'Hostel', '$500 ', 'Subway', '$20 '],
 [29.0, 'Female', 'Spanish', 'Airbnb', '$700 ', 'Car rental', '$250 '],
 [35.0, 'Male', 'British', 'Hotel', '$1,000 ', 'Train', '$200 '],
 [23.0, 'Female', 'Indian', 'Hostel', '$400 ', 'Bus', '$50 '],
 [30.0, 'Male', 'Brazilian', 'Airbnb', '$800 ', 'Train', '$150 '],
 [28.0, 'Female', 'Canadian', 'Hotel', '$1,400 ', 'Flight', '$800 '],
 [27.0, 'Female', 'South Korean', 'Airbnb', '$900 ', 'Car rental', '$200 '],
 [25.0, 'Male', 'American', 'Hostel', '$500 ', 'Bus', '$100 '],
 [31.0, 'Female', 'Canadian', 'Hotel', '$1,200 ', 'Train', '$300 '],
 [31.0, 'Female', 'Dutch', 'Hotel', '1100', 'Plane', '700'],
 [24.0, 'Male', 'Korean', 'Hostel', '400', 'Train', '150'],
 [29.0, 'Female', 'Indian', 'Airbnb', '500', 'Bus', '50'],
 [41.0, 'Male', 'American', 'Hotel', '1500', 'Plane', '500'],
 [27.0, 'Female', 'Spanish', 'Hostel', '600', 'Plane', '600'],
 [55.0, 'Male', 'British', 'Airbnb', '900', 'Train', '100'],
 [30.0, 'Female', 'Brazilian', 'Hotel', '1200', 'Plane', '700'],
 [45.0, 'Male', 'American', 'Resort', '2200', 'Plane', '800'],
 [28.0, 'Female', 'Chinese', 'Hostel', '500', 'Plane', '900'],
 [33.0, 'Male', 'Canadian', 'Airbnb', '800', 'Train', '150'],
 [25.0, 'Female', 'American', 'Hotel', '1400', 'Plane', '600'],
 [38.0, 'Female', 'Australian', 'Airbnb', '$350 ', 'Bus', '$75 '],
 [27.0, 'Male', 'Korean', 'Hotel', '$900 ', 'Car rental', '$400 '],
 [31.0, 'Female', 'American', 'Hostel', '$180 ', 'Train', '$120 '],
 [42.0, 'Male', 'British', 'Airbnb', '$500 ', 'Plane', '$800 '],
 [37.0, 'Female', 'Canadian', 'Hotel', '$700 ', 'Train', '$100 '],
 [20.0, 'Male', 'American', 'Airbnb', '$400 ', 'Plane', '$600 '],
 [33.0, 'Female', 'Australian', 'Hostel', '$150 ', 'Bus', '$50 '],
 [28.0, 'Female', 'British', 'Hotel', '$1,000 ', 'Car rental', '$500 '],
 [25.0, 'Male', 'Korean', 'Airbnb', '$600 ', 'Car rental', '$300 '],
 [45.0, 'Male', 'Canadian', 'Hostel', '$200 ', 'Train', '$150 '],
 [30.0, 'Female', 'American', 'Hotel', '$800 ', 'Plane', '$500 '],
 [31.0, 'Female', 'Spanish', 'Hotel', '$1,100 ', 'Train', '$150 '],
 [34.0, 'Male', 'Korean', 'Resort', '$2,000 ', 'Plane', '$800 '],
 [24.0, 'Female', 'Vietnamese', 'Hotel', '$1,400 ', 'Train', '$100 '],
 [40.0, 'Male', 'Indian', 'Hostel', '$400 ', 'Plane', '$500 '],
 [29.0, 'Female', 'Italian', 'Airbnb', '$700 ', 'Train', '$80 '],
 [32.0, 'Male', 'Australian', 'Hotel', '$1,000 ', 'Plane', '$600 '],
 [27.0, 'Female', 'American', 'Airbnb', '$600 ', 'Bus', '$100 '],
 [45.0, 'Male', 'Japanese', 'Hotel', '$1,200 ', 'Plane', '$800 '],
 [35.0, 'Female', 'British', 'Hotel', '$1,200 ', 'Train', '$150 '],
 [28.0, 'Male', 'Chinese', 'Resort', '$1,500 ', 'Plane', '$700 '],
 [30.0, 'Female', 'American', 'Hotel', '$900 ', 'Plane', '$400 '],
 [32.0, 'Male', 'Scottish', 'Hotel', '900', 'Train', '150'],
 [26.0, 'Female', 'Moroccan', 'Riad', '600', 'Flight', '400'],
 [48.0, 'Male', 'German', 'Hotel', '1400', 'Flight', '700'],
 [29.0, 'Female', 'Chinese', 'Resort', '3000', 'Flight', '1200'],
 [36.0, 'Male', 'Spanish', 'Airbnb', '800', 'Train', '100'],
 [27.0, 'Female', 'Mexican', 'Hotel', '1000', 'Flight', '500'],
 [39.0, 'Male', 'Emirati', 'Resort', '2500', 'Flight', '800'],
 [31.0, 'Female', 'Dutch', 'Hotel', '1200', 'Train', '200'],
 [25.0, 'Male', 'Brazilian', 'Airbnb', '900', 'Flight', '600'],
 [33.0, 'Female', 'Australian', 'Hostel', '500', 'Flight', '1200'],
 [42.0, 'Male', 'American', 'Hotel', '1500', 'Flight', '800'],
 [26.0, 'Female', 'Vietnamese', 'Airbnb', '700', 'Train', '200'],
 [29.0, 'Female', 'British', 'Hotel', '2000', 'Flight', '1000'],
 [45.0, 'Male', 'Korean', 'Villa', '1000', 'Flight', '700'],
 [28.0, 'Female', 'Canadian', 'Resort', '800', 'Flight', '500'],
 [35.0, 'Male', 'American', 'Hotel', '1200', 'Flight', '600']]

In [ ]:
df.sort() # Melakukan pengurutan elemen dalam list atau struktur data dengan metode sort()
df # Menampilkan list atau struktur data setelah diurutkan

[[24.0, 'Male', 'Korean', 'Hotel', '1200', 'Plane', '700'],
 [25.0, 'Female', 'Spanish', 'Airbnb', '6000', 'Airplane', '2500'],
 [26.0, 'Female', 'Chinese', 'Airbnb', '800', 'Plane', '1000'],
 [26.0, 'Male', 'Canada', 'Hostel', '300', 'Plane', '900'],
 [27.0, 'Female', 'American', 'Hotel', '8000', 'Airplane', '2500'],
 [27.0, 'Male', 'Greece', 'Airbnb', '1000', 'Ferry', '150'],
 [28.0, 'Female', 'British', 'Airbnb', '7000', 'Train', '1500'],
 [28.0, 'Female', 'South Korea', 'Airbnb', '800', 'Train', '500'],
 [28.0, 'Male', 'American', 'Hostel', '400', 'Plane', '700'],
 [29.0, 'Female', 'Canadian', 'Hotel', '5000', 'Airplane', '3000'],
 [29.0, 'Female', 'Korean', 'Hostel', '500', 'Plane', '800'],
 [29.0,
  'Female',
  'United Arab Emirates',
  'Hotel',
  '1500',
  'Car rental',
  '300'],
 [30.0, 'Female', 'Chinese', 'Airbnb', '900', 'Plane', '1000'],
 [30.0, 'Female', 'Taiwan', 'Resort', '1500', 'Plane', '1200'],
 [31.0, 'Female', 'Australian', 'Hotel', '6000', 'Airplane', '3000'],
 [31.0, 'Female', 'Italy', 'Hotel', '1100', 'Train', '250'],
 [32.0, 'Female', 'American', 'Hotel', '1000', 'Plane', '700'],
 [33.0, 'Female', 'Canadian', 'Hotel', '800', 'Plane', '800'],
 [33.0, 'Male', 'Cambodia', 'Hostel', '200', 'Plane', '500'],
 [34.0, 'Male', 'Chinese', 'Hostel', '2000', 'Train', '1000'],
 [35.0, 'Female', 'Korean', 'Airbnb', '700', 'Plane', '900'],
 [35.0, 'Male', 'American', 'Hotel', '5000', 'Airplane', '2500'],
 [35.0, 'Male', 'USA', 'Hotel', '1000', 'Plane', '800'],
 [37.0, 'Male', 'Brazilian', 'Hostel', '2500', 'Car', '2000'],
 [38.0, 'Female', 'United Kingdom', 'Hotel', '900', 'Train', '150'],
 [38.0, 'Male', 'Korean', 'Hotel', '900', 'Train', '400'],
 [39.0, 'Male', 'New Zealander', 'Hotel', '7000', 'Train', '2500'],
 [41.0, 'Male', 'American', 'Hotel', '1300', 'Plane', '600'],
 [41.0, 'Male', 'Germany', 'Hotel', '$600 ', 'Train', '$150 '],
 [42.0, 'Male', 'Hong Kong', 'Hotel', '1200', 'Car rental', '200'],
 [42.0, 'Male', 'Korean', 'Airbnb', '4000', 'Train', '1500'],
 [45.0, 'Male', 'Singapore', 'Villa', '2000', 'Plane', '700'],
 [45.0, 'Male', 'South African', 'Hostel', '3000', 'Car', '2000'],
 [nan, nan, nan, nan, nan, nan, nan],
 [24.0, 'Female', 'Emirati', 'Hotel', '1000 USD', 'Plane', '800 USD'],
 [25.0, 'Female', 'Taiwanese', 'Resort', '600 USD', 'Plane', '700 USD'],
 [26.0, 'Male', 'Vietnamese', 'Airbnb', '400 USD', 'Train', '100 USD'],
 [27.0, 'Female', 'Korean', 'Hotel', '400 USD', 'Plane', '400 USD'],
 [27.0, 'Female', 'Korean', 'Hotel', '800 USD', 'Train', '150 USD'],
 [27.0, 'Female', 'Spain', 'Airbnb', '$500 ', 'Plane', '$1,500 '],
 [28.0, 'Female', 'Canada', 'Airbnb', '$400 ', 'Train', '$200 '],
 [28.0, 'Female', 'Korean', 'Airbnb', '500 USD', 'Train', '300 USD'],
 [29.0, 'Female', 'South Korea', 'Villa', '$1,200 ', 'Plane', '$1,000 '],
 [29.0, 'Male', 'American', 'Hotel', '1000 USD', 'Train', '200 USD'],
 [29.0, 'Male', 'British', 'Hostel', '300 USD', 'Plane', '400 USD'],
 [30.0, 'Female', 'Italian', 'Hostel', '200 USD', 'Plane', '350 USD'],
 [31.0, 'Female', 'American', 'Airbnb', '700 USD', 'Car rental', '200 USD'],
 [31.0, 'Female', 'Taiwan', 'Hotel', '$700 ', 'Plane', '$900 '],
 [31.0, 'Male', 'South African', 'Guesthouse', '400 USD', 'Car', '300 USD'],
 [32.0, 'Female', 'British', 'Resort', '700 USD', 'Plane', '800 USD'],
 [33.0, 'Male', 'Brazil', 'Hotel', '$900 ', 'Car rental', '$400 '],
 [33.0, 'Male', 'Indonesian', 'Villa', '1500 USD', 'Car rental', '300 USD'],
 [35.0, 'Female', 'South Korean', 'Resort', '500 USD', 'Plane', '800 USD'],
 [35.0, 'Male', 'American', 'Hotel', '800 USD', 'Plane', '500 USD'],
 [35.0, 'Male', 'USA', 'Hotel', '$500 ', 'Plane', '$800 '],
 [37.0, 'Female', 'British', 'Resort', '1800', 'Plane', '1000'],
 [37.0, 'Female', 'UK', 'Hotel', '$600 ', 'Plane', '$700 '],
 [38.0, 'Male', 'Australian', 'Hotel', '900 USD', 'Plane', '600 USD'],
 [41.0, 'Male', 'American', 'Hotel', '100', nan, nan],
 [41.0, 'Male', 'Italian', 'Hotel', '1300', 'Train', '100'],
 [42.0, 'Female', 'Mexican', 'Resort', '800 USD', 'Plane', '500 USD'],
 [42.0, 'Female', 'Spanish', 'Resort', '1200 USD', 'Plane', '700 USD'],
 [42.0, 'Male', 'Japan', 'Hostel', '$300 ', 'Train', '$100 '],
 [45.0, 'Male', 'Australian', 'Hotel', '900 USD', 'Plane', '600 USD'],
 [45.0, 'Male', 'South Korea', 'Hostel', '$200 ', 'Plane', '$1,200 '],
 [46.0, 'Male', 'British', 'Hotel', '1200 USD', 'Plane', '700 USD'],
 [47.0, 'Male', 'Canadian', 'Hotel', '1200', 'Train', '500'],
 [50.0, 'Male', 'China', 'Airbnb', '$800 ', 'Car rental', '$300 '],
 [60.0, 'Male', 'American', 'Hotel', '1500 USD', 'Plane', '1000 USD'],
 [nan, nan, nan, nan, nan, nan, nan],
 [20.0, 'Male', 'American', 'Airbnb', '$400 ', 'Plane', '$600 '],
 [23.0, 'Female', 'Indian', 'Hostel', '$400 ', 'Bus', '$50 '],
 [24.0, 'Female', 'Vietnamese', 'Hotel', '$1,400 ', 'Train', '$100 '],
 [24.0, 'Male', 'Korean', 'Hostel', '400', 'Train', '150'],
 [25.0, 'Female', 'American', 'Hotel', '1400', 'Plane', '600'],
 [25.0, 'Male', 'American', 'Hostel', '$500 ', 'Bus', '$100 '],
 [25.0, 'Male', 'American', 'Vacation rental', '1000', 'Plane', '800'],
 [25.0, 'Male', 'Brazilian', 'Airbnb', '900', 'Flight', '600'],
 [25.0, 'Male', 'Korean', 'Airbnb', '$600 ', 'Car rental', '$300 '],
 [26.0, 'Female', 'Moroccan', 'Riad', '600', 'Flight', '400'],
 [26.0, 'Female', 'Vietnamese', 'Airbnb', '700', 'Train', '200'],
 [26.0, 'Male', 'Chinese', 'Hotel', '$1,200 ', 'Car rental', '$300 '],
 [27.0, 'Female', 'American', 'Airbnb', '$600 ', 'Bus', '$100 '],
 [27.0, 'Female', 'Mexican', 'Hotel', '1000', 'Flight', '500'],
 [27.0, 'Female', 'South Korean', 'Airbnb', '$900 ', 'Car rental', '$200 '],
 [27.0, 'Female', 'Spanish', 'Hostel', '600', 'Plane', '600'],
 [27.0, 'Male', 'American', 'Resort', '2200', 'Plane', '1000'],
 [27.0, 'Male', 'Korean', 'Hotel', '$900 ', 'Car rental', '$400 '],
 [27.0, 'Male', 'South Korean', 'Hostel', '$500 ', 'Subway', '$20 '],
 [28.0, 'Female', 'British', 'Hotel', '$1,000 ', 'Car rental', '$500 '],
 [28.0, 'Female', 'Canadian', 'Hotel', '$1,400 ', 'Flight', '$800 '],
 [28.0, 'Female', 'Canadian', 'Resort', '800', 'Flight', '500'],
 [28.0, 'Female', 'Chinese', 'Hostel', '500', 'Plane', '900'],
 [28.0, 'Male', 'Chinese', 'Resort', '$1,500 ', 'Plane', '$700 '],
 [28.0, 'Male', 'Japanese', 'Hostel', '400', 'Train', '300'],
 [29.0, 'Female', 'British', 'Hotel', '2000', 'Flight', '1000'],
 [29.0, 'Female', 'British', 'Vacation rental', '800', 'Car rental', '200'],
 [29.0, 'Female', 'Chinese', 'Resort', '3000', 'Flight', '1200'],
 [29.0, 'Female', 'Indian', 'Airbnb', '500', 'Bus', '50'],
 [29.0, 'Female', 'Italian', 'Airbnb', '$700 ', 'Train', '$80 '],
 [29.0, 'Female', 'Spanish', 'Airbnb', '$700 ', 'Car rental', '$250 '],
 [30.0, 'Female', 'American', 'Hotel', '$800 ', 'Plane', '$500 '],
 [30.0, 'Female', 'American', 'Hotel', '$900 ', 'Plane', '$400 '],
 [30.0, 'Female', 'Brazilian', 'Hotel', '1200', 'Plane', '700'],
 [30.0, 'Male', 'Brazilian', 'Airbnb', '$800 ', 'Train', '$150 '],
 [31.0, 'Female', 'American', 'Hostel', '$180 ', 'Train', '$120 '],
 [31.0, 'Female', 'Canadian', 'Hotel', '$1,200 ', 'Train', '$300 '],
 [31.0, 'Female', 'Dutch', 'Hotel', '1100', 'Plane', '700'],
 [31.0, 'Female', 'Dutch', 'Hotel', '1200', 'Train', '200'],
 [31.0, 'Female', 'Spanish', 'Hotel', '$1,100 ', 'Train', '$150 '],
 [31.0, 'Female', 'Spanish', 'Vacation rental', '900', 'Plane', '700'],
 [32.0, 'Male', 'Australian', 'Hotel', '$1,000 ', 'Plane', '$600 '],
 [32.0, 'Male', 'Scottish', 'Hotel', '900', 'Train', '150'],
 [33.0, 'Female', 'Australian', 'Hostel', '$150 ', 'Bus', '$50 '],
 [33.0, 'Female', 'Australian', 'Hostel', '500', 'Flight', '1200'],
 [33.0, 'Female', 'Indian', 'Hostel', '300', 'Plane', '700'],
 [33.0, 'Female', 'Italian', 'Airbnb', '$800 ', 'Train', '$100 '],
 [33.0, 'Male', 'Canadian', 'Airbnb', '800', 'Train', '150'],
 [34.0, 'Male', 'Korean', 'Resort', '$2,000 ', 'Plane', '$800 '],
 [35.0, 'Female', 'American', 'Hotel', '1200', 'Plane', '800'],
 [35.0, 'Female', 'British', 'Hotel', '$1,200 ', 'Train', '$150 '],
 [35.0, 'Male', 'American', 'Hotel', '1200', 'Flight', '600'],
 [35.0, 'Male', 'British', 'Hotel', '$1,000 ', 'Train', '$200 '],
 [36.0, 'Male', 'Spanish', 'Airbnb', '800', 'Train', '100'],
 [37.0, 'Female', 'Canadian', 'Hotel', '$700 ', 'Train', '$100 '],
 [38.0, 'Female', 'Australian', 'Airbnb', '$350 ', 'Bus', '$75 '],
 [39.0, 'Female', 'French', 'Hotel', '1100', 'Train', '200'],
 [39.0, 'Male', 'Emirati', 'Resort', '2500', 'Flight', '800'],
 [40.0, 'Male', 'Indian', 'Hostel', '$400 ', 'Plane', '$500 '],
 [41.0, 'Male', 'American', 'Hotel', '1500', 'Plane', '500'],
 [42.0, 'Male', 'American', 'Hotel', '1500', 'Flight', '800'],
 [42.0, 'Male', 'British', 'Airbnb', '$500 ', 'Plane', '$800 '],
 [43.0, 'Male', 'Australian', 'Hotel', '1500', 'Plane', '1200'],
 [45.0, 'Male', 'American', 'Resort', '2200', 'Plane', '800'],
 [45.0, 'Male', 'Canadian', 'Hostel', '$200 ', 'Train', '$150 '],
 [45.0, 'Male', 'Japanese', 'Hotel', '$1,200 ', 'Plane', '$800 '],
 [45.0, 'Male', 'Korean', 'Villa', '1000', 'Flight', '700'],
 [48.0, 'Male', 'German', 'Hotel', '1400', 'Flight', '700'],
 [55.0, 'Male', 'British', 'Airbnb', '900', 'Train', '100']]

In [ ]:
#menjalankan program
linked_list = LinkedList()

while True:
    print("\nMenu:")#kode menampilkan menu
    print("1. Insert Data at the Beginning")
    print("2. Insert Data at the End")
    print("3. Delete Data from the Beginning")
    print("4. Delete Data from the End")
    print("5. Print All Data")
    print("6. Quit")

    choice = input("Enter your choice (1/ 2/ 3/ 4/ 5/ 6): ")#memanggil kode menu dengan angka

    if choice == "1": #menambahkan data di awal
      Traveler_age = int(input("Masukkan umur: "))
      Traveler_gender = input("Masukkan jenis kelamin: ")
      Travel_nasionality = input("Masukkan kebangsaan: ")
      Accomodation_type = input("Jenis penginapan: ")
      Accomodation_cost = int(input("Masukkan pengeluaran penginapan: $"))
      Transportation_type = input("Masukkan jenis transportasi: ")
      Transportation_cost = int(input("Masukkan pengeluaran transportasi: $"))
      linked_list.add_at_beginning(Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost)
    elif choice == "2": #menambahkan data di akhir
      Traveler_age = int(input("Masukkan umur: "))
      Traveler_gender = input("Masukkan jenis kelamin: ")
      Travel_nasionality = input("Masukkan kebangsaan: ")
      Accomodation_type = input("Jenis penginapan: ")
      Accomodation_cost = int(input("Masukkan pengeluaran penginapan: $"))
      Transportation_type = input("Masukkan jenis transportasi: ")
      Transportation_cost = int(input("Masukkan pengeluaran transportasi: $"))
      linked_list.add_at_end(Traveler_age, Traveler_gender, Travel_nasionality, Accomodation_type, Accomodation_cost, Transportation_type, Transportation_cost)
    elif choice == "3": #menghapus data dari awal
        linked_list.delete_from_beginning()
    elif choice == "4": #menghapus data dari akhir
        linked_list.delete_from_end()
    elif choice == "5": #mencetak semua data yang telah ditambahkan
        linked_list.print_data()
    elif choice == "6": #memberhentikan program
        break  #keluar looping
    else:
        print("Invalid choice. Please try again.") #kode tidak akan dijalnkan

Menu:
1. Insert Data at the Beginning
2. Insert Data at the End
3. Delete Data from the Beginning
4. Delete Data from the End
5. Print All Data
6. Quit
Enter your choice (1/ 2/ 3/ 4/ 5/ 6): 6